# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viterbi_demo', '0002_result_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='choice',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='fileName',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='sessionID',
            new_name='session_ID',
        ),
        migrations.AddField(
            model_name='choice',
            name='user_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='length',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
