# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viterbi_demo', '0003_auto_20160217_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
